version: 2
updates:
    # "/web"
    - package-ecosystem: "npm"
      directory: "/web"
      schedule:
          interval: "monthly"
          day: "monday"
      commit-message:
          prefix: "chore(web)"
      reviewers:
          - "enesyukselx"
      assignees:
          - "enesyukselx"
      labels:
          - "dependencies"
          - "web"
      groups:
          security-updates:
              applies-to: security-updates
              patterns:
                  - "*"
          minor-updates:
              applies-to: version-updates
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"

    # "/cronjob"
    - package-ecosystem: "npm"
      directory: "/cronjob"
      schedule:
          interval: "monthly"
          day: "monday"
      commit-message:
          prefix: "chore(cronjob)"
      reviewers:
          - "enesyukselx"
      assignees:
          - "enesyukselx"
      labels:
          - "dependencies"
          - "cronjob"
      groups:
          security-updates:
              applies-to: security-updates
              patterns:
                  - "*"
          minor-updates:
              applies-to: version-updates
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"

    # "/slack"
    - package-ecosystem: "npm"
      directory: "/slack"
      schedule:
          interval: "monthly"
          day: "monday"
      commit-message:
          prefix: "chore(slack)"
      reviewers:
          - "enesyukselx"
      assignees:
          - "enesyukselx"
      labels:
          - "dependencies"
          - "slack"
      groups:
          security-updates:
              applies-to: security-updates
              patterns:
                  - "*"
          minor-updates:
              applies-to: version-updates
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"
