version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/web"
      schedule:
          interval: "weekly"
          day: "saturday"
      open-pull-requests-limit: 10
      labels:
          - "dependencies"
          - "web"
      commit-message:
          prefix: "chore(web)"
          include: "scope"
      groups:
          minor-patches:
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"
          major-updates:
              patterns:
                  - "*"
              update-types:
                  - "major"

    - package-ecosystem: "npm"
      directory: "/cronjob"
      schedule:
          interval: "weekly"
          day: "saturday"
      open-pull-requests-limit: 10
      labels:
          - "dependencies"
          - "cronjob"
      commit-message:
          prefix: "chore(cronjob)"
          include: "scope"
      groups:
          minor-patches:
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"
          major-updates:
              patterns:
                  - "*"
              update-types:
                  - "major"

    - package-ecosystem: "npm"
      directory: "/slack"
      schedule:
          interval: "weekly"
          day: "saturday"
      open-pull-requests-limit: 10
      labels:
          - "dependencies"
          - "slack"
      commit-message:
          prefix: "chore(slack)"
          include: "scope"
      groups:
          minor-patches:
              patterns:
                  - "*"
              update-types:
                  - "minor"
                  - "patch"
          major-updates:
              patterns:
                  - "*"
              update-types:
                  - "major"
